name: Request a Quote
description: Share a bit about your project for a quick quote
title: "Quote: <short title>"
labels: ["quote","lead"]
body:
  - type: input
    id: name
    attributes: { label: Your name }
    validations: { required: true }
  - type: input
    id: email
    attributes: { label: Email }
    validations: { required: true }
  - type: dropdown
    id: budget
    attributes: { label: Budget, options: ["Under ","–","–","Over "] }
  - type: dropdown
    id: timeline
    attributes: { label: Timeline, options: ["ASAP","1–2 weeks","This month","Flexible"] }
  - type: textarea
    id: scope
    attributes: { label: Scope, description: "What does success look like?" }
    validations: { required: true }