name: Request a Quote
description: Tell Echo what you need and get a fast quote.
title: 'Quote: <short title>'
labels: ['quote','lead']
body:
  - type: input
    id: name
    attributes: { label: Your name }
    validations: { required: true }
  - type: input
    id: email
    attributes: { label: Email }
    validations: { required: true }
  - type: dropdown
    id: budget
    attributes: { label: Budget, options: ['Under \','\–\','\–\','Over \'] }
  - type: textarea
    id: details
    attributes: { label: Project details, description: 'What does success look like?' }
    validations: { required: true }