name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PowerShell analyze
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Information,Warning,Error

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Prettier check
        run: npx prettier@3 -c .

      - name: Markdown lint
        run: npx markdownlint-cli@0.39 "**/*.md" "!node_modules"
